/** English copy for IT/advanced sections and contact-updates table on /admin. */
export const IT_ADMIN_COPY = {
  contactUpdatesTitle: 'Resident contact and billing messages',
  contactUpdatesSubtitle:
    'Messages from the pay-bill and services forms. Sign in at /admin/login if this list is empty.',
  downloadCsvLabel: 'Download CSV',
  printReportLabel: 'Print report',
  contactUpdatesLoading: 'Loading messages…',
  contactUpdatesLoadError: 'Could not load messages. Sign in at /admin/login or call Town Hall.',
  contactUpdatesRetryLabel: 'Try again',
  noContactUpdates: 'No resident messages yet.',
  connectionKicker: 'Technical check (IT)',
  connectionTitle: 'Test connection to the content database',
  connectionBody: 'For IT troubleshooting only. Clerks do not need to run this.',
  testConnection: 'Test connection',
  testingConnection: 'Testing…',
  connectionSuccess: 'Connected',
  connectionFailed: 'Not connected',
  connectionFailureGuidance:
    'The public site may show backup text until IT fixes environment settings and redeploys.',
  connectionReady: 'Ready to test',
  connectionNotRun: 'Not tested yet',
  lastCheckedLabel: 'Last checked',
  latencyLabel: 'Response time',
  recordCountLabel: 'Sample records',
  sampleTownLabel: 'Sample town name',
  endpointLabel: 'Server',
  regionLabel: 'Region',
  apiKeyLabel: 'Read key',
  apiKeyPresent: 'Present',
  apiKeyMissing: 'Missing',
  troubleLabel: 'Error',
  openAwsConsole: 'Open AWS Console (IT)',
  setupDetailsTitle: 'Setup values (IT)',
  copyValueLabel: 'Copy',
  copiedLabel: 'Copied',
  contentSourceLabel: 'Content source',
  contentSourceStudio: 'Live editor content',
  contentSourceFallback: 'Backup text only',
  contentSourceLoading: 'Loading…',
  contentSourceError: 'Load failed — backup text',
  runtimeConfigLabel: 'Runtime config',
  runtimeConfigPresent: 'Present',
  runtimeConfigMissing: 'Missing',
} as const;
