/** English copy for IT/advanced sections on /admin. */
export const IT_ADMIN_COPY = {
  connectionKicker: 'Technical check (IT)',
  connectionTitle: 'Test connection to the content database',
  connectionBody: 'For IT troubleshooting only. Clerks do not need to run this.',
  testConnection: 'Test connection',
  testingConnection: 'Testing…',
  connectionSuccess: 'Connected',
  connectionFailed: 'Not connected',
  connectionFailureGuidance:
    'The public site may show backup text until IT fixes environment settings and redeploys.',
  connectionReady: 'Ready to test',
  connectionNotRun: 'Not tested yet',
  lastCheckedLabel: 'Last checked',
  latencyLabel: 'Response time',
  recordCountLabel: 'Sample records',
  sampleTownLabel: 'Sample town name',
  endpointLabel: 'Server',
  regionLabel: 'Region',
  apiKeyLabel: 'Read key',
  apiKeyPresent: 'Present',
  apiKeyMissing: 'Missing',
  troubleLabel: 'Error',
  clearWebsiteCache: 'Clear saved website copy',
  clearWebsiteCacheSuccess: 'Saved website copy cleared from this browser.',
  refreshFromDatabase: 'Refresh from database',
  refreshingFromDatabase: 'Refreshing…',
  refreshFromDatabaseHelp:
    'Fetches the latest content from AppSync into this browser. The public site also refreshes from the database on each page load.',
  openAwsConsole: 'Open AWS Console (IT)',
  setupDetailsTitle: 'Setup values (IT)',
  copyValueLabel: 'Copy',
  copiedLabel: 'Copied',
  contentSourceLabel: 'Content source',
  contentSourceStudio: 'Live editor content',
  contentSourceFallback: 'Backup text only',
  contentSourceLoading: 'Loading…',
  contentSourceError: 'Load failed — backup text',
  runtimeConfigLabel: 'Runtime config',
  runtimeConfigPresent: 'Present',
  runtimeConfigMissing: 'Missing',
} as const;
