name: Site CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: site-ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run:
    uses: ./.github/workflows/git-workflow.yml
    secrets: inherit
